dist: focal
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
services:
  - docker

install: "pip install -r requirements.txt"

script:
  - behave tests/features
  - PYTHONPATH=scripts python -m unittest discover tests

